### REGISTER USER 1
POST http://localhost:5001/users
Content-Type: application/json

{
    "lastname": "Tom100",
    "firstname": "tom100",
    "email": "tom100@tom.com",
    "password": "Azerty123456!",
    "role": "admin"
}

### GET USER 1
GET http://localhost:5001/users/3fd21d58-516f-4323-9da0-998f5b9180fc

### LOGIN USER 1
POST http://localhost:5001/security/login
Content-Type: application/json

{
    "email": "tom100@tom.com",
    "password": "Azerty123456!"
}

### TRY Token Bearer USER 1 (ADMIN ONLY)
GET http://localhost:5001/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIzZmQyMWQ1OC01MTZmLTQzMjMtOWRhMC05OThmNWI5MTgwZmMiLCJmdWxsTmFtZSI6InRvbTEwMCBUb20xMDAiLCJpYXQiOjE3MjYwODgzMjJ9.fR0UzLrGID27KxmpTj9Jyhk7wQVYb8cKNAInfwBn40k

### REGISTER USER 2
POST http://localhost:5001/users
Content-Type: application/json

{
    "lastname": "Tom101",
    "firstname": "tom101",
    "email": "tom101@tom.com",
    "password": "Azerty123456!",
    "role": "admin"
}

### GET USER 2
GET http://localhost:5001/users/22c40581-3b14-4cf9-879f-4ed2fb69251c

### LOGIN USER 2
POST http://localhost:5001/security/login
Content-Type: application/json

{
    "email": "tom101@tom.com",
    "password": "Azerty123456!"
}

### TRY Token Bearer USER 2 (ADMIN ONLY)
GET http://localhost:5001/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIyMmM0MDU4MS0zYjE0LTRjZjktODc5Zi00ZWQyZmI2OTI1MWMiLCJmdWxsTmFtZSI6InRvbTEwMSBUb20xMDEiLCJpYXQiOjE3MjYwODgzNjl9.bOjKEAe523hmKCDcRhF8f90JzzOphJUzvHY6NAkXMoQ